### ISSUE TITLE
Fix Typos in Readme?

### ISSUE THREAD

**Issue by connorlanewhite** [matty-at-rdc/an-encouraging-word#1]
Seems like there are some typos in the readme. If you're willing to accept pull requests from outside contributors, I could submit the following?
<img width="825" alt="recommended changes" src="https://user-images.githubusercontent.com/13944198/220750804-6f91a42a-21c7-44e3-8f39-bcc72457ff59.png">

Anyways - big fan of your work!

**Comment by matty-at-rdc** [comment]
All fine callouts. I fixed SOME of these!
